name: Add discuss during sync label

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-label:
    name: Add discuss during sync
    uses: ponylang/shared-workflows/.github/workflows/add-discuss-during-sync-label.yml@main
    secrets:
      token: ${{ secrets.PONYLANG_TOKEN }}
