name: Breakage against ponyc latest

on:
  repository_dispatch:
    types: [shared-docker-builders-updated]

concurrency:
  group: breakage-against-ponyc-latest
  cancel-in-progress: true

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: make ci config=release
