name: Changelog bot

on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md

jobs:
  changelog-bot:
    name: Changelog bot
    uses: ponylang/shared-workflows/.github/workflows/changelog-bot-update.yml@main
    secrets:
      token: ${{ secrets.PONYLANG_TOKEN }}
